/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faicebroiskious;

import org.apache.thrift.TException;
import resources.Grafo.*;

/**
 *
 * @author lucascesarnf
 */
public class Perfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JTextField();
        OrientacaoLabel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        identidadeLabel = new javax.swing.JComboBox<>();
        cadastrarButton = new javax.swing.JButton();
        IdLabel = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Edite seus dados");

        jLabel2.setText("Nome:");

        nameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameLabelActionPerformed(evt);
            }
        });

        OrientacaoLabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hétero ", "Homo", "Bi" }));
        OrientacaoLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrientacaoLabelActionPerformed(evt);
            }
        });

        jLabel3.setText("Orientação Sexual:");

        jLabel6.setText("Identidade de Gênero:");

        identidadeLabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homem ", "Mulher", "Outrxs" }));
        identidadeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identidadeLabelActionPerformed(evt);
            }
        });

        cadastrarButton.setBackground(new java.awt.Color(153, 204, 255));
        cadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarButton.setText("Atualizar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        IdLabel.setText("Seu ID: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(OrientacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarButton))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IdLabel)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrientacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastrarButton)
                .addGap(18, 18, 18)
                .addComponent(IdLabel)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLabelActionPerformed

    private void OrientacaoLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrientacaoLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrientacaoLabelActionPerformed

    private void identidadeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identidadeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identidadeLabelActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        vertice.desc = nameLabel.getText();
        // System.out.println("Descricao:" + v.desc);
        // System.out.println("nome:" + v.nome);
        vertice.peso = identidadeLabel.getSelectedIndex();
        // System.out.println("peso:" + v.peso);
        vertice.cor =  OrientacaoLabel.getSelectedIndex();
        // System.out.println("cor:" + v.cor);
        try {
            Handler.Client client = ClientTransport.getInstance().getCLient();
            if(client.updateVertice(vertice)){
                System.out.println("Atualizado com sucesso");
            }else{
                System.out.println("Não atualizou");
            }
        } catch (TException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed
    public void startView(Vertice v){
        this.vertice = v;
        nameLabel.setText(v.desc);
        IdLabel.setText("Seu ID de compartilhamento: "+v.nome);
        OrientacaoLabel.setSelectedIndex(v.cor);
        identidadeLabel.setSelectedIndex((int) v.peso);
    }
    private Vertice vertice;

    public Vertice getVertice() {
        return vertice;
    }

    public void setVertice(Vertice vertice) {
        this.vertice = vertice;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLabel;
    private javax.swing.JComboBox<String> OrientacaoLabel;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JComboBox<String> identidadeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameLabel;
    // End of variables declaration//GEN-END:variables
}
